/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Display;

/**
 *
 * @author marco
 */
public class OperacoesJFrame extends javax.swing.JFrame {
    Display display;
    /**
     * Creates new form OperacoesJFrame
     */
    public OperacoesJFrame() {
        this.display = new Display();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultjPanel = display.panel();
        OperacoesjTabbedPane = new javax.swing.JTabbedPane();
        eq1GraujPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coeficienteAngular = new javax.swing.JTextField();
        coeficienteLinear = new javax.swing.JTextField();
        submitEq1Grau = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        eq1GraujPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coeficienteAngular1 = new javax.swing.JTextField();
        coeficienteLinear1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        coeficienteLinear2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout resultjPanelLayout = new javax.swing.GroupLayout(resultjPanel);
        resultjPanel.setLayout(resultjPanelLayout);
        resultjPanelLayout.setHorizontalGroup(
            resultjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        resultjPanelLayout.setVerticalGroup(
            resultjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Coeficiente Angular");

        jLabel2.setText("Coeficiente Linear");

        coeficienteAngular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteAngularActionPerformed(evt);
            }
        });

        coeficienteLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteLinearActionPerformed(evt);
            }
        });

        submitEq1Grau.setText("Exibir gráfico");
        submitEq1Grau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEq1GrauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eq1GraujPanel1Layout = new javax.swing.GroupLayout(eq1GraujPanel1);
        eq1GraujPanel1.setLayout(eq1GraujPanel1Layout);
        eq1GraujPanel1Layout.setHorizontalGroup(
            eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eq1GraujPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitEq1Grau)
                    .addGroup(eq1GraujPanel1Layout.createSequentialGroup()
                        .addGroup(eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coeficienteLinear, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(coeficienteAngular))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        eq1GraujPanel1Layout.setVerticalGroup(
            eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eq1GraujPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(coeficienteAngular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eq1GraujPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(coeficienteLinear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitEq1Grau)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        OperacoesjTabbedPane.addTab("Equação de 1º grau", eq1GraujPanel1);

        jLabel3.setText("Coeficiente Principal (a)");

        jLabel4.setText("Coeficiente Secundário (b)");

        coeficienteAngular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteAngular1ActionPerformed(evt);
            }
        });

        coeficienteLinear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteLinear1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exibir gráfico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Termo Independente (c)");

        coeficienteLinear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coeficienteLinear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eq1GraujPanel2Layout = new javax.swing.GroupLayout(eq1GraujPanel2);
        eq1GraujPanel2.setLayout(eq1GraujPanel2Layout);
        eq1GraujPanel2Layout.setHorizontalGroup(
            eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eq1GraujPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coeficienteAngular1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(coeficienteLinear1)
                    .addComponent(coeficienteLinear2))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eq1GraujPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );
        eq1GraujPanel2Layout.setVerticalGroup(
            eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eq1GraujPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(coeficienteAngular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coeficienteLinear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eq1GraujPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(coeficienteLinear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(eq1GraujPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(eq1GraujPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        OperacoesjTabbedPane.addTab("Equação de 2º grau", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OperacoesjTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OperacoesjTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitEq1GrauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEq1GrauActionPerformed
        // TODO add your handling code here:
        double coeficienteAngularAux = Double.parseDouble(this.coeficienteAngular.getText());
        double coeficienteLinearAux = Double.parseDouble(this.coeficienteLinear.getText());
        display.setEquacao1Grau(coeficienteAngularAux, coeficienteLinearAux);
    }//GEN-LAST:event_submitEq1GrauActionPerformed

    private void coeficienteLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteLinearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteLinearActionPerformed

    private void coeficienteAngularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteAngularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteAngularActionPerformed

    private void coeficienteAngular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteAngular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteAngular1ActionPerformed

    private void coeficienteLinear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteLinear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteLinear1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void coeficienteLinear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coeficienteLinear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coeficienteLinear2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacoesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacoesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacoesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacoesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacoesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OperacoesjTabbedPane;
    private javax.swing.JTextField coeficienteAngular;
    private javax.swing.JTextField coeficienteAngular1;
    private javax.swing.JTextField coeficienteLinear;
    private javax.swing.JTextField coeficienteLinear1;
    private javax.swing.JTextField coeficienteLinear2;
    private javax.swing.JPanel eq1GraujPanel1;
    private javax.swing.JPanel eq1GraujPanel2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel resultjPanel;
    private javax.swing.JButton submitEq1Grau;
    // End of variables declaration//GEN-END:variables
}
